#
# Settings
#
# This file contains settings for various parts of the code
# Add your own modifications as necessary

Setup:
  gpu: 'cuda:3'
  gpu_num: '3'
  gpu_fraction: 0.5

Train:
  experiment_name: self_supervised
  data_path: /scratch/lapnet/coronal
  save_dir: /home/studghoul1/lapnet/logs/checkpoints/torch
  lr: 1e-5
  batch_size: 64
  clip: 1.0
  training_mode: 'supervised' # or 'self_supervised'
  epochs: 12
  wdecay: 0.00001
  mask: False

Evaluate:
  IDs : ['patient_035_slice13']
  checkpoint_path: /home/studghoul1/lapnet/logs/checkpoints/torch/ckpt0.pt
  save_path: home/studghoul1/lapnet/results
  acc_list': [1, 8, 30]
  patch_size: 33
  stride_size: 2
  smooth_wind_size: 17
  data_path: /mnt/qdata/projects/MoCo/LAPNet/coronal_test_data
  img_size: (256,256)



