#
# Settings
#
# This file contains settings for various parts of the code
# Add your own modifications as necessary

Setup:
  architecture_version: 1
  dimensionality: 2D
  mode_run: test # or train_unsupervised or train_supervised
  slicing_mode: tapering
  # GPU device IDs to train_supervised on
  gpu_list: '3'
  gpu_num_gb: 10
  supervised: False

Train:
  training_data:
    create_data: False
    # num of workers used when creating data
    num_workers: 6
    saving_dir: /home/studghoul1/lapnet/data/3D_dataset
    #num of times a subject is undersampled and used to create data
    num_subject_us: 2
    # num of patches extracted from one slice
    box_num: 200
    # undersampling method
    mask_type: drUS
    # selected subjects and slices for training
    subjectsIDs: /home/studghoul1/lapnet/create_data/training_subjects_names.txt
    slice_info_coronal: /home/studghoul1/lapnet/create_data/slice_info_resp_coronal.ods
    slice_info_sagittal: /home/studghoul1/lapnet/create_data/slice_info_resp_sagital.ods
    slice_info_axial: /home/studghoul1/lapnet/create_data/slice_info_resp_axial.ods
    ImgPath: /mnt/data/rawdata/MoCo/LAPNet/resp/motion_data
    FlowPath: /mnt/data/rawdata/MoCo/LAPNet/resp/LAP
    # mask the motion field to remove background
    mask_Flow: True
    # tell if input data is normalized otherwise it will be normalized
    normalized_img: False


  Experiment:
    data_fetch_method: generator # or tfrecords
    experiment_name: 2D_self_supervised
    checkpoint_file: 2D_self_supervised
    data_path: /scratch/lapnet/coronal
    num_epochs: 10
    batch_size: 64
    learning_rate: 1e-4
    optimizer: 'Adam'
    num_workers: 2
    # stores summaries and final model checkpoints
    logs_path: /home/studghoul1/lapnet/logs/checkpoints
    weights_path: False
    loss:  'photometric'

Test:
  test_data:
    create_data: False
    num_workers: 1
    saving_dir: /home/studghoul1/lapnet/data/3D_testData
    mask_type: drUS
    aug_type: real
    list_us: [1, 8, 30]
    direction: coronal
    subjectsIDs: /home/studghoul1/lapnet/create_data/test_subjects_names.txt
    slice_info_coronal: /home/studghoul1/lapnet/create_data/slice_info_resp_coronal.ods
    slice_info_sagittal: /home/studghoul1/lapnet/create_data/slice_info_resp_sagital.ods
    slice_info_axial: /home/studghoul1/lapnet/create_data/slice_info_resp_axial.ods
    ImgPath: /mnt/data/rawdata/MoCo/LAPNet/resp/motion_data
    FlowPath: /mnt/data/rawdata/MoCo/LAPNet/resp/LAP
    mask_Flow: True
    normalized_img: False

  Evaluate:
    weights: /home/studghoul1/lapnet/logs/checkpoints/checkpoints/2D_self_supervised/2D_self_supervised/2D_self_supervised_01.hd5f
    padding : True
    slice_size: 33
    slice_stride: 2
    smooth_wind_size: 17
    batch_size: 64
    slice_num: 10
    direction: coronal
    acc: [1, 8, 30]
    ID: patient_004_slice13
    save_path: /home/studghoul1/lapnet/results
    path_data: /scratch/lapnet/coronal_test_data



